apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  sourceRepos:
    - '*'                    # allow any repo
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
