apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/mrcpngn/gitops-repo.git'
    targetRevision: main
    path: charts/grafana
    helm:
      valueFiles:
      - ../../env/grafana/values.yaml
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

