apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-dev
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/mrcpngn/gitops-repo.git'
    targetRevision: main
    path: charts/podinfo
    helm:
      valueFiles:
      - ../../env/podinfo/dev-values.yaml
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

